# -*- coding: utf-8 -*-
"""Final KAAM AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YjdtH-QgZ3LCr00S3vZ-wgjix6qymNs
"""

!pip install --quiet streamlit pyngrok gTTS

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from gtts import gTTS
# import os
# import base64
# 
# # Helper function to get base64 encoded image
# def get_image_as_base64(path):
#     if os.path.exists(path):
#         with open(path, "rb") as image_file:
#             return base64.b64encode(image_file.read()).decode('utf-8')
#     return None
# 
# # Function to add custom CSS for colorful background
# def add_custom_css():
#     st.markdown(
#         f"""
#         <style>
#         .stApp {{
#             background: linear-gradient(to right, #ee9ca7, #ffdde1);
#             background-attachment: fixed;
#         }}
#         .sidebar .sidebar-content {{
#             background: linear-gradient(to right, #ee9ca7, #ffdde1);
#         }}
#         </style>
#         """,
#         unsafe_allow_html=True
#     )
# 
# # Apply custom CSS
# add_custom_css()
# 
# # Job data (full data including the Painter category and its translations)
# informal_jobs_data = {
#     "Teashop": {
#         "image_url": "https://via.placeholder.com/300/FF5733/FFFFFF?text=Teashop",
#         "language_data": {
#             "en": {
#                 "procedure": [
#                     "Find a busy street or area with good footfall.",
#                     "Get basic utensils, stove, milk, tea powder, and cups.",
#                     "Maintain hygiene and cleanliness.",
#                     "Serve with quick customer service."
#                 ],
#                 "productivity_tips": [
#                     "Offer different flavors like masala tea, lemon tea.",
#                     "Keep the area clean to attract customers.",
#                     "Offer discount for regulars."
#                 ],
#                 "new_ideas": [
#                     "Eco-friendly paper cups with custom branding.",
#                     "Offer snacks like biscuits and samosas.",
#                     "Tea subscription services to offices nearby."
#                 ],
#                 "legal_procedures": [
#                     "Street vendor license from local municipal office.",
#                     "FSSAI registration for food safety compliance."
#                 ],
#                 "loan_process": [
#                     "Approach local bank under PM Mudra Yojana scheme.",
#                     "Get documents: Aadhar, residence proof, and income declaration.",
#                     "Use the loan for setting up or upgrading."
#                 ],
#                 "investment_ideas": [
#                     "Start with ₹5000 for basic setup.",
#                     "Upgrade to mobile tea van if demand increases."
#                 ]
#             },
#             "kn": {
#                 "procedure": [
#                     "ಹೆಚ್ಚು ಜನಸಂದಣಿ ಇರುವ ಸ್ಥಳವನ್ನು ಹುಡುಕಿ.",
#                     "ಮೂಲ ಪಾತ್ರೆಗಳು, ಸ್ಟೌವ್, ಹಾಲು, ಚಹಾ ಪುಡಿ ಮತ್ತು ಕಪ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ.",
#                     "ಸ್ವಚ್ಛತೆ ಮತ್ತು ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ.",
#                     "ವೇಗದ ಗ್ರಾಹಕ ಸೇವೆಯೊಂದಿಗೆ ಸೇವೆ ಸಲ್ಲಿಸಿ."
#                 ],
#                 "productivity_tips": [
#                     "ಮಸಾಲಾ ಚಹಾ, ನಿಂಬೆ ಚಹಾ ಮುಂತಾದ ವಿಭಿನ್ನ ರುಚಿಗಳನ್ನು ನೀಡಿ.",
#                     "ಗ್ರಾಹಕರನ್ನು ಆಕರ್ಷಿಸಲು ಪ್ರದೇಶವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ.",
#                     "ನಿಯಮಿತ ಗ್ರಾಹಕರಿಗೆ ರಿಯಾಯಿತಿ ನೀಡಿ."
#                 ],
#                 "new_ideas": [
#                     "ಕಸ್ಟಮ್ ಬ್ರ್ಯಾಂಡಿಂಗ್‌ನೊಂದಿಗೆ ಪರಿಸರ ಸ್ನೇಹಿ ಕಾಗದದ ಕಪ್‌ಗಳು.",
#                     "ಬಿಸ್ಕತ್ತು ಮತ್ತು ಸಮೋಸಗಳಂತಹ ತಿಂಡಿಗಳನ್ನು ನೀಡಿ.",
#                     "ಹತ್ತಿರದ ಕಚೇರಿಗಳಿಗೆ ಚಹಾ ಚಂದಾದಾರಿಕೆ ಸೇವೆಗಳನ್ನು ನೀಡಿ."
#                 ],
#                 "legal_procedures": [
#                     "ಸ್ಥಳೀಯ ನಗರಸಭೆ ಕಚೇರಿಯಿಂದ ಬೀದಿ ವ್ಯಾಪಾರಿ ಪರವಾನಗಿ.",
#                     "ಆಹಾರ ಸುರಕ್ಷತೆಗಾಗಿ FSSAI ನೋಂದಣಿ."
#                 ],
#                 "loan_process": [
#                     "PM ಮುದ್ರಾ ಯೋಜನೆ ಅಡಿಯಲ್ಲಿ ಸ್ಥಳೀಯ ಬ್ಯಾಂಕ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ.",
#                     "ಆಧಾರ್, ವಸತಿ ಪುರಾವೆ ಮತ್ತು ಆದಾಯ ಘೋಷಣೆಯಂತಹ ದಾಖಲೆಗಳನ್ನು ಪಡೆಯಿರಿ.",
#                     "ಸ್ಥಾಪನೆ ಅಥವಾ ನವೀಕರಣಕ್ಕಾಗಿ ಸಾಲವನ್ನು ಬಳಸಿ."
#                 ],
#                 "investment_ideas": [
#                     "ಮೂಲ ಸೆಟಪ್‌ಗಾಗಿ ₹5000 ದೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ.",
#                     "ಬೇಡಿಕೆ ಹೆಚ್ಚಾದರೆ ಮೊಬೈಲ್ ಟೀ ವ್ಯಾನ್‌ಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ."
#                 ]
#             },
#             "hi": {
#                 "procedure": [
#                     "अधिक भीड़भाड़ वाली जगह ढूंढें।",
#                     "बुनियादी बर्तन, स्टोव, दूध, चाय पत्ती और कप प्राप्त करें।",
#                     "स्वच्छता और सफ़ाई बनाए रखें।",
#                     "तेज़ ग्राहक सेवा के साथ परोसें।"
#                 ],
#                 "productivity_tips": [
#                     "मसाला चाय, नींबू चाय जैसे विभिन्न स्वाद प्रदान करें।",
#                     "ग्राहकों को आकर्षित करने के लिए क्षेत्र को साफ़ रखें।",
#                     "नियमित ग्राहकों को छूट प्रदान करें।"
#                 ],
#                 "new_ideas": [
#                     "कस्टम ब्रांडिंग के साथ पर्यावरण के अनुकूल पेपर कप।",
#                     "बिसकुट और समोसे जैसे स्नैक्स पेश करें।",
#                     "आस-पास के कार्यालयों को चाय सदस्यता सेवाएँ प्रदान करें।"
#                 ],
#                 "legal_procedures": [
#                     "स्थानीय नगर पालिका कार्यालय से स्ट्रीट वेंडर लाइसेंस।",
#                     "खाद्य सुरक्षा अनुपालन के लिए FSSAI पंजीकरण।"
#                 ],
#                 "loan_process": [
#                     "पीएम मुद्रा योजना के तहत स्थानीय बैंक से संपर्क करें।",
#                     "दस्तावेज़ प्राप्त करें: आधार, निवास प्रमाण और आय घोषणा।",
#                     "स्थापना या उन्नयन के लिए ऋण का उपयोग करें।"
#                 ],
#                 "investment_ideas": [
#                     "बुनियादी सेटअप के लिए ₹5000 से शुरुआत करें।",
#                     "यदि मांग बढ़ती है तो मोबाइल चाय वैन में अपग्रेड करें।"
#                 ]
#             }
#         }
#     },
#     "Tailoring": {
#         "image_url": "https://via.placeholder.com/300/33FF57/FFFFFF?text=Tailoring",
#         "language_data": {
#             "en": {
#                 "procedure": [
#                     "Get a sewing machine and basic tailoring tools.",
#                     "Set up a workspace at home or rent a small shop.",
#                     "Advertise locally using word-of-mouth or flyers."
#                 ],
#                 "productivity_tips": [
#                     "Keep learning new designs and patterns.",
#                     "Take measurements accurately and maintain customer books.",
#                     "Deliver orders on time."
#                 ],
#                 "new_ideas": [
#                     "Offer online booking and pickup/drop service.",
#                     "Teach tailoring to others for extra income."
#                 ],
#                 "legal_procedures": [
#                     "Register as self-employed with local authorities.",
#                     "GST not needed if annual income is below threshold."
#                 ],
#                 "loan_process": [
#                     "Apply for MSME loan at a bank.",
#                     "Provide estimate for machine and rent."
#                 ],
#                 "investment_ideas": [
#                     "Start under ₹10,000 if working from home.",
#                     "Invest in embroidery machine as business grows."
#                 ]
#             },
#             "kn": {
#                 "procedure": [
#                     "ಒಂದು ಹೊಲಿಗೆ ಯಂತ್ರ ಮತ್ತು ಮೂಲ ಟೈಲರಿಂಗ್ ಉಪಕರಣಗಳನ್ನು ಪಡೆಯಿರಿ.",
#                     "ಮನೆಯಲ್ಲಿ ಕೆಲಸದ ಸ್ಥಳವನ್ನು ಸ್ಥಾಪಿಸಿ ಅಥವಾ ಸಣ್ಣ ಅಂಗಡಿಯನ್ನು ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.",
#                     "ಮೌಖಿಕವಾಗಿ ಅಥವಾ ಫ್ಲೈಯರ್‌ಗಳನ್ನು ಬಳಸಿ ಸ್ಥಳೀಯವಾಗಿ ಪ್ರಚಾರ ಮಾಡಿ."
#                 ],
#                 "productivity_tips": [
#                     "ಹೊಸ ವಿನ್ಯಾಸಗಳು ಮತ್ತು ಮಾದರಿಗಳನ್ನು ಕಲಿಯುತ್ತಿರಿ.",
#                     "ನಿಖರವಾಗಿ ಅಳತೆಗಳನ್ನು ತೆಗೆದುಕೊಂಡು ಗ್ರಾಹಕರ ಪುಸ್ತಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
#                     "ಆದೇಶಗಳನ್ನು ಸಮಯಕ್ಕೆ ತಲುಪಿಸಿ."
#                 ],
#                 "new_ideas": [
#                     "ಆನ್‌ಲೈನ್ ಬುಕಿಂಗ್ ಮತ್ತು ಪಿಕಪ್/ಡ್ರಾಪ್ ಸೇವೆಯನ್ನು ಒದಗಿಸಿ.",
#                     "ಹೆಚ್ಚುವರಿ ಆದಾಯಕ್ಕಾಗಿ ಇತರರಿಗೆ ಟೈಲರಿಂಗ್ ಕಲಿಸಿ."
#                 ],
#                 "legal_procedures": [
#                     "ಸ್ಥಳೀಯ ಅಧಿಕಾರಿಗಳೊಂದಿಗೆ ಸ್ವಯಂ ಉದ್ಯೋಗಿಯಾಗಿ ನೋಂದಾಯಿಸಿ.",
#                     "ವಾರ್ಷಿಕ ಆದಾಯ ಮಿತಿಗಿಂತ ಕಡಿಮೆಯಿದ್ದರೆ GST ಅಗತ್ಯವಿಲ್ಲ."
#                 ],
#                 "loan_process": [
#                     "ಬ್ಯಾಂಕಿನಲ್ಲಿ MSME ಸಾಲಕ್ಕಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
#                     "ಯಂತ್ರ ಮತ್ತು ಬಾಡಿಗೆಗಾಗಿ ಅಂದಾಜು ನೀಡಿ."
#                 ],
#                 "investment_ideas": [
#                     "ಮನೆಯಿಂದ ಕೆಲಸ ಮಾಡುತ್ತಿದ್ದರೆ ₹10,000 ಕ್ಕಿಂತ ಕಡಿಮೆ ವೆಚ್ಚದಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ.",
#                     "ವ್ಯಾಪಾರ ಬೆಳೆದಂತೆ ಎಂಬ್ರಾಯ್ಡರಿ ಯಂತ್ರದಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡಿ."
#                 ]
#             },
#             "hi": {
#                 "procedure": [
#                     "एक सिलाई मशीन और बुनियादी सिलाई उपकरण प्राप्त करें।",
#                     "घर पर एक कार्यस्थल स्थापित करें या एक छोटी दुकान किराए पर लें।",
#                     "मुंह से या फ़्लायर का उपयोग करके स्थानीय स्तर पर विज्ञापन करें।"
#                 ],
#                 "productivity_tips": [
#                     "नए डिज़ाइन और पैटर्न सीखते रहें।",
#                     "सटीक माप लें और ग्राहक किताबें बनाए रखें।",
#                     "समय पर ऑर्डर डिलीवर करें।"
#                 ],
#                 "new_ideas": [
#                     "ऑनलाइन बुकिंग और पिकअप/ड्रॉप सेवा प्रदान करें।",
#                     "अतिरिक्त आय के लिए दूसरों को सिलाई सिखाएं।"
#                 ],
#                 "legal_procedures": [
#                     "स्थानीय अधिकारियों के साथ स्व-नियोजित के रूप पर पंजीकरण करें।",
#                     "यदि वार्षिक आय सीमा से कम है तो जीएसटी की आवश्यकता नहीं है।"
#                 ],
#                 "loan_process": [
#                     "बैंक में एमएसएमई ऋण के लिए आवेदन करें।",
#                     "मशीन और किराए के लिए अनुमान प्रदान करें।"
#                 ],
#                 "investment_ideas": [
#                     "घर से काम करते हैं तो ₹10,000 से कम में शुरू करें।",
#                     "व्यवसाय बढ़ने पर कढ़ाई मशीन में निवेश करें।"
#                 ]
#             }
#         }
#     },
#     "Vegetable Seller": {
#         "image_url": "https://via.placeholder.com/300/3357FF/FFFFFF?text=Vegetable+Seller",
#         "language_data": {
#             "en": {
#                 "procedure": [
#                     "Purchase vegetables early from wholesale market.",
#                     "Set up cart or roadside stall.",
#                     "Maintain quality and freshness."
#                 ],
#                 "productivity_tips": [
#                     "Display items attractively.",
#                     "Give small offers like 1 free lemon per ₹50 spent."
#                 ],
#                 "new_ideas": [
#                     "Start WhatsApp orders for home delivery.",
#                     "Partner with housing societies for bulk sales."
#                 ],
#                 "legal_procedures": [
#                     "Get street vendor license.",
#                     "Follow weight standards."
#                 ],
#                 "loan_process": [
#                     "Apply under PM SVANidhi Yojana.",
#                     "Use loan for better weighing machine or pushcart."
#                 ],
#                 "investment_ideas": [
#                     "Begin with ₹2000-₹3000 stock.",
#                     "Use profits to scale slowly."
#                 ]
#             },
#             "kn": {
#                 "procedure": [
#                     "ಸಗಟು ಮಾರುಕಟ್ಟೆಯಿಂದ ಬೇಗನೆ ತರಕಾರಿಗಳನ್ನು ಖರೀದಿಸಿ.",
#                     "ಗಾಡಿ ಅಥವಾ ರಸ್ತೆಬದಿಯ ಮಳಿಗೆಯನ್ನು ಸ್ಥಾಪಿಸಿ.",
#                     "ಗುಣಮಟ್ಟ ಮತ್ತು ತಾಜಾತನವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ."
#                 ],
#                 "productivity_tips": [
#                     "ವಸ್ತುಗಳನ್ನು ಆಕರ್ಷಕವಾಗಿ ಪ್ರದರ್ಶಿಸಿ.",
#                     "₹50 ಖರ್ಚು ಮಾಡಿದರೆ 1 ನಿಂಬೆ ಹಣ್ಣು ಉಚಿತದಂತಹ ಸಣ್ಣ ಕೊಡುಗೆಗಳನ್ನು ನೀಡಿ."
#                 ],
#                 "new_ideas": [
#                     "ಮನೆ ವಿತರಣೆಗಾಗಿ WhatsApp ಆದೇಶಗಳನ್ನು ಪ್ರಾರಂಭಿಸಿ.",
#                     "ಬೃಹತ್ ಮಾರಾಟಕ್ಕಾಗಿ ವಸತಿ ಸಂಘಗಳೊಂದಿಗೆ ಪಾಲುದಾರಿಕೆ ಮಾಡಿ."
#                 ],
#                 "legal_procedures": [
#                     "ಬೀದಿ ವ್ಯಾಪಾರಿ ಪರವಾನಗಿ ಪಡೆಯಿರಿ.",
#                     "ತೂಕದ ಮಾನದಂಡಗಳನ್ನು ಅನುಸರಿಸಿ."
#                 ],
#                 "loan_process": [
#                     "PM ಸ್वनिಧಿ ಯೋಜನೆ ಅಡಿಯಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
#                     "ಉತ್ತಮ ತೂಕದ ಯಂತ್ರ ಅಥವಾ ತಳ್ಳುಗಾಡಿಗಾಗಿ ಸಾಲವನ್ನು ಬಳಸಿ."
#                 ],
#                 "investment_ideas": [
#                     "₹2000-₹3000 ಸ್ಟಾಕ್‌ನೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ.",
#                     "ನಿಧಾನವಾಗಿ ವಿಸ್ತರಿಸಲು ಲಾಭವನ್ನು ಬಳಸಿ."
#                 ]
#             },
#             "hi": {
#                 "procedure": [
#                     "थोक बाजार से जल्दी सब्जियां खरीदें।",
#                     "गाड़ी या सड़क के किनारे स्टाल लगाएं।",
#                     "गुणवत्ता और ताज़गी बनाए रखें।"
#                 ],
#                 "productivity_tips": [
#                     "वस्तुओं को आकर्षक रूप से प्रदर्शित करें।",
#                     "₹50 खर्च करने पर 1 नींबू मुफ्त जैसे छोटे ऑफ़र दें।"
#                 ],
#                 "new_ideas": [
#                     "होम डिलीवरी के लिए व्हाट्सएप ऑर्डर शुरू करें।",
#                     "थोक बिक्री के लिए हाउसिंग सोसाइटी के साथ साझेदारी करें।"
#                 ],
#                 "legal_procedures": [
#                     "स्ट्रीट वेंडर लाइसेंस प्राप्त करें।",
#                     "वजन मानकों का पालन करें।"
#                 ],
#                 "loan_process": [
#                     "पीएम स्वनिधि योजना के तहत आवेदन करें।",
#                     "बेहतर वजन मशीन या ठेले के लिए ऋण का उपयोग करें।"
#                 ],
#                 "investment_ideas": [
#                     "₹2000-₹3000 के स्टॉक से शुरुआत करें।",
#                     "धीरे-धीरे विस्तार करने के लिए मुनाफे का उपयोग करें।"
#                 ]
#             }
#         }
#     },
#     "Mobile Repair": {
#         "image_url": "https://via.placeholder.com/300/FF33CC/FFFFFF?text=Mobile+Repair",
#         "language_data": {
#             "en": {
#                 "procedure": [
#                     "Complete a short training course.",
#                     "Buy tools and a second-hand workbench.",
#                     "Set up roadside shop or share space."
#                 ],
#                 "productivity_tips": [
#                     "Be honest with customers.",
#                     "Stock fast-moving parts like chargers and screens."
#                 ],
#                 "new_ideas": [
#                     "Offer doorstep service.",
#                     "Post ads on social media for your work."
#                 ],
#                 "legal_procedures": [
#                     "Register with shop license if in a shop.",
#                     "Issue receipts with contact number."
#                 ],
#                 "loan_process": [
#                     "Check bank schemes for skill-based businesses.",
#                     "Present course certificate and ID."
#                 ],
#                 "investment_ideas": [
#                     "Start under ₹15,000 with second-hand tools.",
#                     "Offer second-hand phones for extra income."
#                 ]
#             },
#             "kn": {
#                 "procedure": [
#                     "ಸಣ್ಣ ತರಬೇತಿ ಕೋರ್ಸ್ ಪೂರ್ಣಗೊಳಿಸಿ.",
#                     "ಉಪಕರಣಗಳು ಮತ್ತು ಸೆಕೆಂಡ್ ಹ್ಯಾಂಡ್ ವರ್ಕ್‌ಬೆಂಚ್ ಖರೀದಿಸಿ.",
#                     "ರಸ್ತೆಬದಿಯ ಅಂಗಡಿಯನ್ನು ಸ್ಥಾಪಿಸಿ ಅಥವಾ ಜಾಗವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ."
#                 ],
#                 "productivity_tips": [
#                     "ಗ್ರಾಹಕರೊಂದಿಗೆ ಪ್ರಾಮಾಣಿಕವಾಗಿರಿ.",
#                     "ಚಾರ್ಜರ್‌ಗಳು ಮತ್ತು ಪರದೆಗಳಂತಹ ವೇಗವಾಗಿ ಮಾರಾಟವಾಗುವ ಭಾಗಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ."
#                 ],
#                 "new_ideas": [
#                     "ಮನೆ ಬಾಗಿಲಿಗೆ ಸೇವೆಯನ್ನು ಒದಗಿಸಿ.",
#                     "ನಿಮ್ಮ ಕೆಲಸಕ್ಕಾಗಿ ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದಲ್ಲಿ ಜಾಹೀರಾತುಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ."
#                 ],
#                 "legal_procedures": [
#                     "ಅಂಗಡಿಯಲ್ಲಿದ್ದರೆ ಅಂಗಡಿ ಪರವಾನಗಿಯೊಂದಿಗೆ ನೋಂದಾಯಿಸಿ.",
#                     "ಸಂಪರ್ಕ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ರಸೀದಿಗಳನ್ನು ನೀಡಿ."
#                 ],
#                 "loan_process": [
#                     "ಕೌಶಲ್ಯ ಆಧಾರಿತ ವ್ಯವಹಾರಗಳಿಗಾಗಿ ಬ್ಯಾಂಕ್ ಯೋಜನೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
#                     "ಕೋರ್ಸ್ ಪ್ರಮಾಣಪತ್ರ ಮತ್ತು ID ಅನ್ನು ಪ್ರಸ್ತುತಪಡಿಸಿ."
#                 ],
#                 "investment_ideas": [
#                     "ಸೆಕೆಂಡ್ ಹ್ಯಾಂಡ್ ಉಪಕರಣಗಳೊಂದಿಗೆ ₹15,000 ಕ್ಕಿಂತ ಕಡಿಮೆ ವೆಚ್ಚದಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ.",
#                     "ಹೆಚ್ಚುವರಿ ಆದಾಯಕ್ಕಾಗಿ ಸೆಕೆಂಡ್ ಹ್ಯಾಂಡ್ ಫೋನ್‌ಗಳನ್ನು ನೀಡಿ."
#                 ]
#             },
#             "hi": {
#                 "procedure": [
#                     "एक छोटा प्रशिक्षण पाठ्यक्रम पूरा करें।",
#                     "उपकरण और एक सेकंड-हैंड वर्कबेंच खरीदें।",
#                     "सड़क के किनारे दुकान स्थापित करें या जगह साझा करें।"
#                 ],
#                 "productivity_tips": [
#                     "ग्राहकों के साथ ईमानदार रहें।",
#                     "चार्जर और स्क्रीन जैसे तेजी से बिकने वाले पुर्जे स्टॉक करें।"
#                 ],
#                 "new_ideas": [
#                     "डोरस्टेप सेवा प्रदान करें।",
#                     "अपने काम के लिए विज्ञापन पोस्ट करें।"
#                 ],
#                 "legal_procedures": [
#                     "यदि दुकान में हैं तो दुकान लाइसेंस के साथ पंजीकरण करें।",
#                     "संपर्क नंबर के साथ रसीदें जारी करें।"
#                 ],
#                 "loan_process": [
#                     "कौशल-आधारित व्यवसायों के लिए बैंक योजनाओं की जाँच करें।",
#                     "पाठ्यक्रम प्रमाणपत्र और आईडी प्रस्तुत करें।"
#                 ],
#                 "investment_ideas": [
#                     "सेकंड-हैंड उपकरणों के साथ ₹15,000 से कम में शुरू करें।",
#                     "अतिरिक्त आय के लिए सेकंड-हैंड फ़ोन पेश करें।"
#                 ]
#             }
#         }
#     },
#     "Rickshaw Driver": {
#         "image_url": "https://via.placeholder.com/300/CCFF33/FFFFFF?text=Rickshaw+Driver",
#         "language_data": {
#             "en": {
#                 "procedure": [
#                     "Buy or rent an auto rickshaw.",
#                     "Get license and badge.",
#                     "Know routes and traffic rules."
#                 ],
#                 "productivity_tips": [
#                     "Be polite to passengers.",
#                     "Maintain vehicle and keep it clean."
#                 ],
#                 "new_ideas": [
#                     "Join ride-hailing apps if eligible.",
#                     "Offer package delivery in off-hours."
#                 ],
#                 "legal_procedures": [
#                     "Commercial driving license.",
#                     "Permit from RTO and insurance."
#                 ],
#                 "loan_process": [
#                     "Get vehicle loan from bank or NBFC.",
#                     "Use EMI plan to repay."
#                 ],
#                 "investment_ideas": [
#                     "Down payment of around ₹25,000–₹50,000.",
#                     "Save daily to buy your own rickshaw."
#                 ]
#             },
#             "kn": {
#                 "procedure": [
#                     "ಆಟೋ ರಿಕ್ಷಾವನ್ನು ಖರೀದಿಸಿ ಅಥವಾ ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.",
#                     "ಪರವಾನಗಿ ಮತ್ತು ಬ್ಯಾಡ್ಜ್ ಪಡೆಯಿರಿ.",
#                     "ಮಾರ್ಗಗಳು ಮತ್ತು ಸಂಚಾರ ನಿಯಮಗಳನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ."
#                 ],
#                 "productivity_tips": [
#                     "ಪ್ರಯಾಣಿಕರೊಂದಿಗೆ ಸೌಜನ್ಯದಿಂದಿರಿ.",
#                     "ವಾಹನವನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ಅದನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ."
#                 ],
#                 "new_ideas": [
#                     "ಅರ್ಹರಾಗಿದ್ದರೆ ರೈಡ್-ಹೇಲಿಂಗ್ ಅಪ್ಲಿಕೇಶನ್‌ಗಳಿಗೆ ಸೇರಿಕೊಳ್ಳಿ.",
#                     "ಅಲಭ್ಯ ಸಮಯದಲ್ಲಿ ಪ್ಯಾಕೇಜ್ ವಿತರಣೆಯನ್ನು ನೀಡಿ."
#                 ],
#                 "legal_procedures": [
#                     "ವಾಣಿಜ್ಯ ಚಾಲನಾ ಪರವಾನಗಿ.",
#                     "RTO ಮತ್ತು ವಿಮೆಯಿಂದ ಅನುಮತಿ."
#                 ],
#                 "loan_process": [
#                     "ಬ್ಯಾಂಕ್ ಅಥವಾ NBFC ಯಿಂದ ವಾಹನ ಸಾಲ ಪಡೆಯಿರಿ.",
#                     "ಮರುಪಾವತಿಸಲು EMI ಯೋಜನೆಯನ್ನು ಬಳಸಿ."
#                 ],
#                 "investment_ideas": [
#                     "ಸುಮಾರು ₹25,000–₹50,000 ಡೌನ್ ಪೇಮೆಂಟ್.",
#                     "ನಿಮ್ಮ ಸ್ವಂತ ರಿಕ್ಷಾವನ್ನು ಖರೀದಿಸಲು ಪ್ರತಿದಿನ ಉಳಿಸಿ."
#                 ]
#             },
#             "hi": {
#                 "procedure": [
#                     "ऑटो रिक्शा खरीदें या किराए पर लें।",
#                     "लाइसेंस और बैज प्राप्त करें।",
#                     "मार्गों और यातायात नियमों को जानें।"
#                 ],
#                 "productivity_tips": [
#                     "यात्रियों के प्रति विनम्र रहें।",
#                     "वाहन का रखरखाव करें और उसे साफ रखें।"
#                 ],
#                 "new_ideas": [
#                     "यदि योग्य हों तो राइड-हेलिंग ऐप्स में शामिल हों।",
#                     "ऑफ-ऑवर में पैकेज डिलीवरी प्रदान करें।"
#                 ],
#                 "legal_procedures": [
#                     "वाणिज्यिक ड्राइविंग लाइसेंस।",
#                     "आरटीओ और बीमा से परमिट।"
#                 ],
#                 "loan_process": [
#                     "बैंक या एनबीएफसी से वाहन ऋण प्राप्त करें।",
#                     "पुनर्भुगतान के लिए ईएमआई योजना का उपयोग करें।"
#                 ],
#                 "investment_ideas": [
#                     "लगभग ₹25,000–₹50,000 का डाउन पेमेंट।",
#                     "अपनी खुद की रिक्शा खरीदने के लिए रोजाना बचत करें।"
#                 ]
#             }
#         }
#     },
#     "Painter": {
#         "image_url": "https://via.placeholder.com/300/FFFF33/000000?text=Painter",
#         "language_data": {
#             "en": {
#                 "procedure": [
#                     "Acquire basic painting tools like brushes, rollers, and paint.",
#                     "Learn different painting techniques and color mixing.",
#                     "Offer services for homes, offices, and commercial spaces."
#                 ],
#                 "productivity_tips": [
#                     "Use high-quality paints for durability and better finish.",
#                     "Prepare surfaces properly (cleaning, priming) for best results.",
#                     "Offer competitive pricing and excellent customer service."
#                 ],
#                 "new_ideas": [
#                     "Specialize in decorative painting or murals.",
#                     "Offer eco-friendly paint options.",
#                     "Create a portfolio of your work online."
#                 ],
#                 "legal_procedures": [
#                     "Register as a sole proprietor or small business.",
#                     "Obtain necessary permits for commercial projects."
#                 ],
#                 "loan_process": [
#                     "Apply for a small business loan to purchase equipment.",
#                     "Maintain good financial records for loan eligibility."
#                 ],
#                 "investment_ideas": [
#                     "Start with an initial investment of ₹10,000-₹20,000 for tools and initial paint stock.",
#                     "Invest in specialized equipment like spray painters as demand grows."
#                 ]
#             },
#             "kn": {
#                 "procedure": [
#                     "ಬ್ರಷ್, ರೋಲರ್‌ಗಳು ಮತ್ತು ಬಣ್ಣದಂತಹ ಮೂಲ ಚಿತ್ರಕಲೆ ಉಪಕರಣಗಳನ್ನು ಪಡೆದುಕೊಳ್ಳಿ.",
#                     "ವಿವಿಧ ಚಿತ್ರಕಲೆ ತಂತ್ರಗಳು ಮತ್ತು ಬಣ್ಣ ಮಿಶ್ರಣವನ್ನು ಕಲಿಯಿರಿ.",
#                     "ಮನೆಗಳು, ಕಚೇರಿಗಳು ಮತ್ತು ವಾಣಿಜ್ಯ ಸ್ಥಳಗಳಿಗೆ ಸೇವೆಗಳನ್ನು ನೀಡಿ."
#                 ],
#                 "productivity_tips": [
#                     "ಬಾಳಿಕೆ ಮತ್ತು ಉತ್ತಮ ಮುಕ್ತಾಯಕ್ಕಾಗಿ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಬಣ್ಣಗಳನ್ನು ಬಳಸಿ.",
#                     "ಉತ್ತಮ ಫಲಿತಾಂಶಗಳಿಗಾಗಿ ಮೇಲ್ಮೈಗಳನ್ನು ಸರಿಯಾಗಿ ತಯಾರಿಸಿ (ಶುದ್ಧೀಕರಣ, ಪ್ರೈಮಿಂಗ್).",
#                     "ಸ್ಪರ್ಧಾತ್ಮಕ ಬೆಲೆ ಮತ್ತು ಅತ್ಯುತ್ತಮ ಗ್ರಾಹಕ ಸೇವೆಯನ್ನು ನೀಡಿ."
#                 ],
#                 "new_ideas": [
#                     "ಅಲಂಕಾರಿಕ ಚಿತ್ರಕಲೆ ಅಥವಾ ಭಿತ್ತಿಚಿತ್ರಗಳಲ್ಲಿ ಪರಿಣತಿ.",
#                     "ಪರಿಸರ ಸ್ನೇಹಿ ಬಣ್ಣದ ಆಯ್ಕೆಗಳನ್ನು ನೀಡಿ.",
#                     "ನಿಮ್ಮ ಕೆಲಸದ ಆನ್‌ಲೈನ್ ಪೋರ್ಟ್‌ಫೋಲಿಯೊವನ್ನು ರಚಿಸಿ."
#                 ],
#                 "legal_procedures": [
#                     "ಏಕಮಾತ್ರ ಮಾಲೀಕರು ಅಥವಾ ಸಣ್ಣ ವ್ಯವಹಾರವಾಗಿ ನೋಂದಾಯಿಸಿ.",
#                     "ವಾಣಿಜ್ಯ ಯೋಜನೆಗಳಿಗೆ ಅಗತ್ಯ ಪರವಾನಗಿಗಳನ್ನು ಪಡೆದುಕೊಳ್ಳಿ."
#                 ],
#                 "loan_process": [
#                     "ಉಪಕರಣಗಳನ್ನು ಖರೀದಿಸಲು ಸಣ್ಣ ವ್ಯಾಪಾರ ಸಾಲಕ್ಕಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
#                     "ಸಾಲ ಅರ್ಹತೆಗಾಗಿ ಉತ್ತಮ ಆರ್ಥಿಕ ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ."
#                 ],
#                 "investment_ideas": [
#                     "ಉಪಕರಣಗಳು ಮತ್ತು ಆರಂಭಿಕ ಬಣ್ಣದ ಸ್ಟಾಕ್‌ಗಾಗಿ ₹10,000-₹20,000 ಆರಂಭಿಕ ಹೂಡಿಕೆಯೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ.",
#                     "ಬೇಡಿಕೆ ಹೆಚ್ಚಾದಂತೆ ಸ್ಪ್ರೇ ಪೇಂಟರ್‌ಗಳಂತಹ ವಿಶೇಷ ಉಪಕರಣಗಳಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡಿ."
#                 ]
#             },
#             "hi": {
#                 "procedure": [
#                     "ब्रश, रोलर और पेंट जैसे बुनियादी पेंटिंग उपकरण प्राप्त करें।",
#                     "विभिन्न पेंटिंग तकनीकें और रंग मिश्रण सीखें।",
#                     "घरों, कार्यालयों और व्यावसायिक स्थानों के लिए सेवाएं प्रदान करें।"
#                 ],
#                 "productivity_tips": [
#                     "स्थायित्व और बेहतर फिनिश के लिए उच्च गुणवत्ता वाले पेंट का उपयोग करें।",
#                     "सर्वोत्तम परिणामों के लिए सतहों को ठीक से तैयार करें (सफाई, प्राइमर)।",
#                     "प्रतिस्पर्धी मूल्य निर्धारण और उत्कृष्ट ग्राहक सेवा प्रदान करें।"
#                 ],
#                 "new_ideas": [
#                     "सजावटी पेंटिंग या भित्तिचित्रों में विशेषज्ञता हासिल करें।",
#                     "पर्यावरण के अनुकूल पेंट विकल्प प्रदान करें।",
#                     "अपने काम का एक ऑनलाइन पोर्टफोलियो बनाएं।"
#                 ],
#                 "legal_procedures": [
#                     "एकमात्र मालिक या छोटे व्यवसाय के रूप में पंजीकरण करें।",
#                     "वाणिज्यिक परियोजनाओं के लिए आवश्यक परमिट प्राप्त करें।"
#                 ],
#                 "loan_process": [
#                     "उपकरण खरीदने के लिए छोटे व्यवसाय ऋण के लिए आवेदन करें।",
#                     "ऋण पात्रता के लिए अच्छे वित्तीय रिकॉर्ड बनाए रखें।"
#                 ],
#                 "investment_ideas": [
#                     "उपकरण और प्रारंभिक पेंट स्टॉक के लिए ₹10,000-₹20,000 के शुरुआती निवेश से शुरू करें।",
#                     "मांग बढ़ने पर स्प्रे पेंटर जैसे विशेष उपकरणों में निवेश करें।"
#                 ]
#             }
#         }
#     }
# }
# 
# # Streamlit App Title and Configuration
# st.set_page_config(layout="wide")
# st.title("Informal Job Helper")
# 
# # Add logo to sidebar
# st.sidebar.image("https://via.placeholder.com/150x50/FF5733/FFFFFF?text=Your+Logo", use_column_width=True)
# 
# # Language selection in sidebar
# language_options = {"English": "en", "ಕನ್ನಡ": "kn", "हिन्दी": "hi"}
# selected_language_name = st.sidebar.selectbox("Select Language", list(language_options.keys()))
# selected_language_code = language_options[selected_language_name]
# 
# # Job selection in sidebar
# job_names = list(informal_jobs_data.keys())
# selected_job = st.sidebar.selectbox("Select Job", job_names)
# 
# # Display job image
# if selected_job and informal_jobs_data[selected_job]["image_url"]:
#     st.image(informal_jobs_data[selected_job]["image_url"], caption=selected_job, width=300)
# 
# if selected_job:
#     job_info = informal_jobs_data[selected_job]["language_data"].get(selected_language_code, informal_jobs_data[selected_job]["language_data"]["en"])
# 
#     st.header(f"Information for {selected_job} ({selected_language_name})")
# 
#     # Helper function to display section and play audio
#     def display_section(title, content_list, lang_code):
#         st.subheader(title)
#         full_text = " ".join(content_list)
#         if full_text:
#             try:
#                 tts = gTTS(text=full_text, lang=lang_code, slow=False)
#                 tts.save("audio.mp3")
#                 audio_file = open("audio.mp3", "rb")
#                 audio_bytes = audio_file.read()
#                 st.audio(audio_bytes, format="audio/mp3")
#                 audio_file.close()
#                 os.remove("audio.mp3") # Clean up the audio file
#             except Exception as e:
#                 st.warning(f"Could not play audio for {title} in {selected_language_name}: {e}")
# 
#         for item in content_list:
#             st.write(f"- {item}")
# 
#     display_section("Procedure", job_info["procedure"], selected_language_code)
#     display_section("Productivity Tips", job_info["productivity_tips"], selected_language_code)
#     display_section("New Ideas", job_info["new_ideas"], selected_language_code)
#     display_section("Legal Procedures", job_info["legal_procedures"], selected_language_code)
#     display_section("Loan Process", job_info["loan_process"], selected_language_code)
#     display_section("Investment Ideas", job_info["investment_ideas"], selected_language_code)
# else:
#     st.info("Please select a job from the sidebar to view information.")

import requests
import time

print("Checking Streamlit app accessibility on http://localhost:8501...")
try:
    # Give Streamlit a moment to start up if it was just launched
    time.sleep(5)
    response = requests.get("http://localhost:8501")
    if response.status_code == 200:
        print("✅ Streamlit app is accessible locally on port 8501!")
    else:
        print(f"⚠️ Streamlit app is running but returned status code: {response.status_code}")
except requests.exceptions.ConnectionError:
    print("❌ Streamlit app is NOT accessible locally on port 8501. It might not be running or is on a different port.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

import streamlit as st
from gtts import gTTS
import base64
import os

# Job data
informal_jobs_data = {
    "Teashop": {
        "image_url": "https://via.placeholder.com/300/FF5733/FFFFFF?text=Teashop",
        "language_data": {
            "en": {
                "procedure": [
                    "Find a busy street or area with good footfall.",
                    "Get basic utensils, stove, milk, tea powder, and cups.",
                    "Maintain hygiene and cleanliness.",
                    "Serve with quick customer service."
                ],
                "productivity_tips": [
                    "Offer different flavors like masala tea, lemon tea.",
                    "Keep the area clean to attract customers.",
                    "Offer discount for regulars."
                ],
                "new_ideas": [
                    "Eco-friendly paper cups with custom branding.",
                    "Offer snacks like biscuits and samosas.",
                    "Tea subscription services to offices nearby."
                ],
                "legal_procedures": [
                    "Street vendor license from local municipal office.",
                    "FSSAI registration for food safety compliance."
                ],
                "loan_process": [
                    "Approach local bank under PM Mudra Yojana scheme.",
                    "Get documents: Aadhar, residence proof, and income declaration.",
                    "Use the loan for setting up or upgrading."
                ],
                "investment_ideas": [
                    "Start with ₹5000 for basic setup.",
                    "Upgrade to mobile tea van if demand increases."
                ]
            },
            "kn": { # Kannada translations for Teashop
                "procedure": [
                    "ಹೆಚ್ಚು ಜನಸಂದಣಿ ಇರುವ ಸ್ಥಳವನ್ನು ಹುಡುಕಿ.",
                    "ಮೂಲ ಪಾತ್ರೆಗಳು, ಸ್ಟೌವ್, ಹಾಲು, ಚಹಾ ಪುಡಿ ಮತ್ತು ಕಪ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ.",
                    "ಸ್ವಚ್ಛತೆ ಮತ್ತು ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ.",
                    "ವೇಗದ ಗ್ರಾಹಕ ಸೇವೆಯೊಂದಿಗೆ ಸೇವೆ ಸಲ್ಲಿಸಿ."
                ],
                "productivity_tips": [
                    "ಮಸಾಲಾ ಚಹಾ, ನಿಂಬೆ ಚಹಾ ಮುಂತಾದ ವಿಭಿನ್ನ ರುಚಿಗಳನ್ನು ನೀಡಿ.",
                    "ಗ್ರಾಹಕರನ್ನು ಆಕರ್ಷಿಸಲು ಪ್ರದೇಶವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ.",
                    "ನಿಯಮಿತ ಗ್ರಾಹಕರಿಗೆ ರಿಯಾಯಿತಿ ನೀಡಿ."
                ],
                "new_ideas": [
                    "ಕಸ್ಟಮ್ ಬ್ರ್ಯಾಂಡಿಂಗ್‌ನೊಂದಿಗೆ ಪರಿಸರ ಸ್ನೇಹಿ ಕಾಗದದ ಕಪ್‌ಗಳು.",
                    "ಬಿಸ್ಕತ್ತು ಮತ್ತು ಸಮೋಸಗಳಂತಹ ತಿಂಡಿಗಳನ್ನು ನೀಡಿ.",
                    "ಹತ್ತಿರದ ಕಚೇರಿಗಳಿಗೆ ಚಹಾ ಚಂದಾದಾರಿಕೆ ಸೇವೆಗಳನ್ನು ನೀಡಿ."
                ],
                "legal_procedures": [
                    "ಸ್ಥಳೀಯ ನಗರಸಭೆ ಕಚೇರಿಯಿಂದ ಬೀದಿ ವ್ಯಾಪಾರಿ ಪರವಾನಗಿ.",
                    "ಆಹಾರ ಸುರಕ್ಷತೆಗಾಗಿ FSSAI ನೋಂದಣಿ."
                ],
                "loan_process": [
                    "PM ಮುದ್ರಾ ಯೋಜನೆ ಅಡಿಯಲ್ಲಿ ಸ್ಥಳೀಯ ಬ್ಯಾಂಕ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ.",
                    "ಆಧಾರ್, ವಸತಿ ಪುರಾವೆ ಮತ್ತು ಆದಾಯ ಘೋಷಣೆಯಂತಹ ದಾಖಲೆಗಳನ್ನು ಪಡೆಯಿರಿ.",
                    "ಸ್ಥಾಪನೆ ಅಥವಾ ನವೀಕರಣಕ್ಕಾಗಿ ಸಾಲವನ್ನು ಬಳಸಿ."
                ],
                "investment_ideas": [
                    "ಮೂಲ ಸೆಟಪ್‌ಗಾಗಿ ₹5000 ದೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ.",
                    "ಬೇಡಿಕೆ ಹೆಚ್ಚಾದರೆ ಮೊಬೈಲ್ ಟೀ ವ್ಯಾನ್‌ಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ."
                ]
            },
            "hi": { # Hindi translations for Teashop
                "procedure": [
                    "अधिक भीड़भाड़ वाली जगह ढूंढें।",
                    "बुनियादी बर्तन, स्टोव, दूध, चाय पत्ती और कप प्राप्त करें।",
                    "स्वच्छता और सफ़ाई बनाए रखें।",
                    "तेज़ ग्राहक सेवा के साथ परोसें।"
                ],
                "productivity_tips": [
                    "मसाला चाय, नींबू चाय जैसे विभिन्न स्वाद प्रदान करें।",
                    "ग्राहकों को आकर्षित करने के लिए क्षेत्र को साफ़ रखें।",
                    "नियमित ग्राहकों को छूट प्रदान करें।"
                ],
                "new_ideas": [
                    "कस्टम ब्रांडिंग के साथ पर्यावरण के अनुकूल पेपर कप।",
                    "बिसकुट और समोसे जैसे स्नैक्स पेश करें।",
                    "आस-पास के कार्यालयों को चाय सदस्यता सेवाएँ प्रदान करें।"
                ],
                "legal_procedures": [
                    "स्थानीय नगर पालिका कार्यालय से स्ट्रीट वेंडर लाइसेंस।",
                    "खाद्य सुरक्षा अनुपालन के लिए FSSAI पंजीकरण।"
                ],
                "loan_process": [
                    "पीएम मुद्रा योजना के तहत स्थानीय बैंक से संपर्क करें।",
                    "दस्तावेज़ प्राप्त करें: आधार, निवास प्रमाण और आय घोषणा।",
                    "स्थापना या उन्नयन के लिए ऋण का उपयोग करें।"
                ],
                "investment_ideas": [
                    "बुनियादी सेटअप के लिए ₹5000 से शुरुआत करें।",
                    "यदि मांग बढ़ती है तो मोबाइल चाय वैन में अपग्रेड करें।"
                ]
            }
        }
    },
    "Tailoring": {
        "image_url": "https://via.placeholder.com/300/33FF57/FFFFFF?text=Tailoring",
        "language_data": {
            "en": {
                "procedure": [
                    "Get a sewing machine and basic tailoring tools.",
                    "Set up a workspace at home or rent a small shop.",
                    "Advertise locally using word-of-mouth or flyers."
                ],
                "productivity_tips": [
                    "Keep learning new designs and patterns.",
                    "Take measurements accurately and maintain customer books.",
                    "Deliver orders on time."
                ],
                "new_ideas": [
                    "Offer online booking and pickup/drop service.",
                    "Teach tailoring to others for extra income."
                ],
                "legal_procedures": [
                    "Register as self-employed with local authorities.",
                    "GST not needed if annual income is below threshold."
                ],
                "loan_process": [
                    "Apply for MSME loan at a bank.",
                    "Provide estimate for machine and rent."
                ],
                "investment_ideas": [
                    "Start under ₹10,000 if working from home.",
                    "Invest in embroidery machine as business grows."
                ]
            },
            "kn": {
                "procedure": [
                    "ಒಂದು ಹೊಲಿಗೆ ಯಂತ್ರ ಮತ್ತು ಮೂಲ ಟೈಲರಿಂಗ್ ಉಪಕರಣಗಳನ್ನು ಪಡೆಯಿರಿ.",
                    "ಮನೆಯಲ್ಲಿ ಕೆಲಸದ ಸ್ಥಳವನ್ನು ಸ್ಥಾಪಿಸಿ ಅಥವಾ ಸಣ್ಣ ಅಂಗಡಿಯನ್ನು ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.",
                    "ಮೌಖಿಕವಾಗಿ ಅಥವಾ ಫ್ಲೈಯರ್‌ಗಳನ್ನು ಬಳಸಿ ಸ್ಥಳೀಯವಾಗಿ ಪ್ರಚಾರ ಮಾಡಿ."
                ],
                "productivity_tips": [
                    "ಹೊಸ ವಿನ್ಯಾಸಗಳು ಮತ್ತು ಮಾದರಿಗಳನ್ನು ಕಲಿಯುತ್ತಿರಿ.",
                    "ನಿಖರವಾಗಿ ಅಳತೆಗಳನ್ನು ತೆಗೆದುಕೊಂಡು ಗ್ರಾಹಕರ ಪುಸ್ತಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
                    "ಆದೇಶಗಳನ್ನು ಸಮಯಕ್ಕೆ ತಲುಪಿಸಿ."
                ],
                "new_ideas": [
                    "ಆನ್‌ಲೈನ್ ಬುಕಿಂಗ್ ಮತ್ತು ಪಿಕಪ್/ಡ್ರಾಪ್ ಸೇವೆಯನ್ನು ಒದಗಿಸಿ.",
                    "ಹೆಚ್ಚುವರಿ ಆದಾಯಕ್ಕಾಗಿ ಇತರರಿಗೆ ಟೈಲರಿಂಗ್ ಕಲಿಸಿ."
                ],
                "legal_procedures": [
                    "ಸ್ಥಳೀಯ ಅಧಿಕಾರಿಗಳೊಂದಿಗೆ ಸ್ವಯಂ ಉದ್ಯೋಗಿಯಾಗಿ ನೋಂದಾಯಿಸಿ.",
                    "ವಾರ್ಷಿಕ ಆದಾಯ ಮಿತಿಗಿಂತ ಕಡಿಮೆಯಿದ್ದರೆ GST ಅಗತ್ಯವಿಲ್ಲ."
                ],
                "loan_process": [
                    "ಬ್ಯಾಂಕಿನಲ್ಲಿ MSME ಸಾಲಕ್ಕಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
                    "ಯಂತ್ರ ಮತ್ತು ಬಾಡಿಗೆಗಾಗಿ ಅಂದಾಜು ನೀಡಿ."
                ],
                "investment_ideas": [
                    "ಮನೆಯಿಂದ ಕೆಲಸ ಮಾಡುತ್ತಿದ್ದರೆ ₹10,000 ಕ್ಕಿಂತ ಕಡಿಮೆ ವೆಚ್ಚದಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ.",
                    "ವ್ಯಾಪಾರ ಬೆಳೆದಂತೆ ಎಂಬ್ರಾಯ್ಡರಿ ಯಂತ್ರದಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡಿ."
                ]
            },
            "hi": {
                "procedure": [
                    "एक सिलाई मशीन और बुनियादी सिलाई उपकरण प्राप्त करें।",
                    "घर पर एक कार्यस्थल स्थापित करें या एक छोटी दुकान किराए पर लें।",
                    "मुंह से या फ़्लायर का उपयोग करके स्थानीय स्तर पर विज्ञापन करें।"
                ],
                "productivity_tips": [
                    "नए डिज़ाइन और पैटर्न सीखते रहें।",
                    "सटीक माप लें और ग्राहक किताबें बनाए रखें।",
                    "समय पर ऑर्डर डिलीवर करें।"
                ],
                "new_ideas": [
                    "ऑनलाइन बुकिंग और पिकअप/ड्रॉप सेवा प्रदान करें।",
                    "अतिरिक्त आय के लिए दूसरों को सिलाई सिखाएं।"
                ],
                "legal_procedures": [
                    "स्थानीय अधिकारियों के साथ स्व-नियोजित के रूप पर पंजीकरण करें।",
                    "यदि वार्षिक आय सीमा से कम है तो जीएसटी की आवश्यकता नहीं है।"
                ],
                "loan_process": [
                    "बैंक में एमएसएमई ऋण के लिए आवेदन करें।",
                    "मशीन और किराए के लिए अनुमान प्रदान करें।"
                ],
                "investment_ideas": [
                    "घर से काम करते हैं तो ₹10,000 से कम में शुरू करें।",
                    "व्यवसाय बढ़ने पर कढ़ाई मशीन में निवेश करें।"
                ]
            }
        }
    },
    "Vegetable Seller": {
        "image_url": "https://via.placeholder.com/300/3357FF/FFFFFF?text=Vegetable+Seller",
        "language_data": {
            "en": {
                "procedure": [
                    "Purchase vegetables early from wholesale market.",
                    "Set up cart or roadside stall.",
                    "Maintain quality and freshness."
                ],
                "productivity_tips": [
                    "Display items attractively.",
                    "Give small offers like 1 free lemon per ₹50 spent."
                ],
                "new_ideas": [
                    "Start WhatsApp orders for home delivery.",
                    "Partner with housing societies for bulk sales."
                ],
                "legal_procedures": [
                    "Get street vendor license.",
                    "Follow weight standards."
                ],
                "loan_process": [
                    "Apply under PM SVANidhi Yojana.",
                    "Use loan for better weighing machine or pushcart."
                ],
                "investment_ideas": [
                    "Begin with ₹2000-₹3000 stock.",
                    "Use profits to scale slowly."
                ]
            },
            "kn": {
                "procedure": [
                    "ಸಗಟು ಮಾರುಕಟ್ಟೆಯಿಂದ ಬೇಗನೆ ತರಕಾರಿಗಳನ್ನು ಖರೀದಿಸಿ.",
                    "ಗಾಡಿ ಅಥವಾ ರಸ್ತೆಬದಿಯ ಮಳಿಗೆಯನ್ನು ಸ್ಥಾಪಿಸಿ.",
                    "ಗುಣಮಟ್ಟ ಮತ್ತು ತಾಜಾತನವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ."
                ],
                "productivity_tips": [
                    "ವಸ್ತುಗಳನ್ನು ಆಕರ್ಷಕವಾಗಿ ಪ್ರದರ್ಶಿಸಿ.",
                    "₹50 ಖರ್ಚು ಮಾಡಿದರೆ 1 ನಿಂಬೆ ಹಣ್ಣು ಉಚಿತದಂತಹ ಸಣ್ಣ ಕೊಡುಗೆಗಳನ್ನು ನೀಡಿ."
                ],
                "new_ideas": [
                    "ಮನೆ ವಿತರಣೆಗಾಗಿ WhatsApp ಆದೇಶಗಳನ್ನು ಪ್ರಾರಂಭಿಸಿ.",
                    "ಬೃಹತ್ ಮಾರಾಟಕ್ಕಾಗಿ ವಸತಿ ಸಂಘಗಳೊಂದಿಗೆ ಪಾಲುದಾರಿಕೆ ಮಾಡಿ."
                ],
                "legal_procedures": [
                    "ಬೀದಿ ವ್ಯಾಪಾರಿ ಪರವಾನಗಿ ಪಡೆಯಿರಿ.",
                    "ತೂಕದ ಮಾನದಂಡಗಳನ್ನು ಅನುಸರಿಸಿ."
                ],
                "loan_process": [
                    "PM ಸ್वनिಧಿ ಯೋಜನೆ ಅಡಿಯಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
                    "ಉತ್ತಮ ತೂಕದ ಯಂತ್ರ ಅಥವಾ ತಳ್ಳುಗಾಡಿಗಾಗಿ ಸಾಲವನ್ನು ಬಳಸಿ."
                ],
                "investment_ideas": [
                    "₹2000-₹3000 ಸ್ಟಾಕ್‌ನೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ.",
                    "ನಿಧಾನವಾಗಿ ವಿಸ್ತರಿಸಲು ಲಾಭವನ್ನು ಬಳಸಿ."
                ]
            },
            "hi": {
                "procedure": [
                    "थोक बाजार से जल्दी सब्जियां खरीदें।",
                    "गाड़ी या सड़क के किनारे स्टाल लगाएं।",
                    "गुणवत्ता और ताज़गी बनाए रखें।"
                ],
                "productivity_tips": [
                    "वस्तुओं को आकर्षक रूप से प्रदर्शित करें।",
                    "₹50 खर्च करने पर 1 नींबू मुफ्त जैसे छोटे ऑफ़र दें।"
                ],
                "new_ideas": [
                    "होम डिलीवरी के लिए व्हाट्सएप ऑर्डर शुरू करें।",
                    "थोक बिक्री के लिए हाउसिंग सोसाइटी के साथ साझेदारी करें।"
                ],
                "legal_procedures": [
                    "स्ट्रीट वेंडर लाइसेंस प्राप्त करें।",
                    "वजन मानकों का पालन करें।"
                ],
                "loan_process": [
                    "पीएम स्वनिधि योजना के तहत आवेदन करें।",
                    "बेहतर वजन मशीन या ठेले के लिए ऋण का उपयोग करें।"
                ],
                "investment_ideas": [
                    "₹2000-₹3000 के स्टॉक से शुरुआत करें।",
                    "धीरे-धीरे विस्तार करने के लिए मुनाफे का उपयोग करें।"
                ]
            }
        }
    },
    "Mobile Repair": {
        "image_url": "https://via.placeholder.com/300/FF33CC/FFFFFF?text=Mobile+Repair",
        "language_data": {
            "en": {
                "procedure": [
                    "Complete a short training course.",
                    "Buy tools and a second-hand workbench.",
                    "Set up roadside shop or share space."
                ],
                "productivity_tips": [
                    "Be honest with customers.",
                    "Stock fast-moving parts like chargers and screens."
                ],
                "new_ideas": [
                    "Offer doorstep service.",
                    "Post ads on social media for your work."
                ],
                "legal_procedures": [
                    "Register with shop license if in a shop.",
                    "Issue receipts with contact number."
                ],
                "loan_process": [
                    "Check bank schemes for skill-based businesses.",
                    "Present course certificate and ID."
                ],
                "investment_ideas": [
                    "Start under ₹15,000 with second-hand tools.",
                    "Offer second-hand phones for extra income."
                ]
            },
            "kn": {
                "procedure": [
                    "ಸಣ್ಣ ತರಬೇತಿ ಕೋರ್ಸ್ ಪೂರ್ಣಗೊಳಿಸಿ.",
                    "ಉಪಕರಣಗಳು ಮತ್ತು ಸೆಕೆಂಡ್ ಹ್ಯಾಂಡ್ ವರ್ಕ್‌ಬೆಂಚ್ ಖರೀದಿಸಿ.",
                    "ರಸ್ತೆಬದಿಯ ಅಂಗಡಿಯನ್ನು ಸ್ಥಾಪಿಸಿ ಅಥವಾ ಜಾಗವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ."
                ],
                "productivity_tips": [
                    "ಗ್ರಾಹಕರೊಂದಿಗೆ ಪ್ರಾಮಾಣಿಕವಾಗಿರಿ.",
                    "ಚಾರ್ಜರ್‌ಗಳು ಮತ್ತು ಪರದೆಗಳಂತಹ ವೇಗವಾಗಿ ಮಾರಾಟವಾಗುವ ಭಾಗಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ."
                ],
                "new_ideas": [
                    "ಮನೆ ಬಾಗಿಲಿಗೆ ಸೇವೆಯನ್ನು ಒದಗಿಸಿ.",
                    "ನಿಮ್ಮ ಕೆಲಸಕ್ಕಾಗಿ ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದಲ್ಲಿ ಜಾಹೀರಾತುಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ."
                ],
                "legal_procedures": [
                    "ಅಂಗಡಿಯಲ್ಲಿದ್ದರೆ ಅಂಗಡಿ ಪರವಾನಗಿಯೊಂದಿಗೆ ನೋಂದಾಯಿಸಿ.",
                    "ಸಂಪರ್ಕ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ರಸೀದಿಗಳನ್ನು ನೀಡಿ."
                ],
                "loan_process": [
                    "ಕೌಶಲ್ಯ ಆಧಾರಿತ ವ್ಯವಹಾರಗಳಿಗಾಗಿ ಬ್ಯಾಂಕ್ ಯೋಜನೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
                    "ಕೋರ್ಸ್ ಪ್ರಮಾಣಪತ್ರ ಮತ್ತು ID ಅನ್ನು ಪ್ರಸ್ತುತಪಡಿಸಿ."
                ],
                "investment_ideas": [
                    "ಸೆಕೆಂಡ್ ಹ್ಯಾಂಡ್ ಉಪಕರಣಗಳೊಂದಿಗೆ ₹15,000 ಕ್ಕಿಂತ ಕಡಿಮೆ ವೆಚ್ಚದಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ.",
                    "ಹೆಚ್ಚುವರಿ ಆದಾಯಕ್ಕಾಗಿ ಸೆಕೆಂಡ್ ಹ್ಯಾಂಡ್ ಫೋನ್‌ಗಳನ್ನು ನೀಡಿ."
                ]
            },
            "hi": {
                "procedure": [
                    "एक छोटा प्रशिक्षण पाठ्यक्रम पूरा करें।",
                    "उपकरण और एक सेकंड-हैंड वर्कबेंच खरीदें।",
                    "सड़क के किनारे दुकान स्थापित करें या जगह साझा करें।"
                ],
                "productivity_tips": [
                    "ग्राहकों के साथ ईमानदार रहें।",
                    "चार्जर और स्क्रीन जैसे तेजी से बिकने वाले पुर्जे स्टॉक करें।"
                ],
                "new_ideas": [
                    "डोरस्टेप सेवा प्रदान करें।",
                    "अपने काम के लिए सोशल मीडिया पर विज्ञापन पोस्ट करें।"
                ],
                "legal_procedures": [
                    "यदि दुकान में हैं तो दुकान लाइसेंस के साथ पंजीकरण करें।",
                    "संपर्क नंबर के साथ रसीदें जारी करें।"
                ],
                "loan_process": [
                    "कौशल-आधारित व्यवसायों के लिए बैंक योजनाओं की जाँच करें।",
                    "पाठ्यक्रम प्रमाणपत्र और आईडी प्रस्तुत करें।"
                ],
                "investment_ideas": [
                    "सेकंड-हैंड उपकरणों के साथ ₹15,000 से कम में शुरू करें।",
                    "अतिरिक्त आय के लिए सेकंड-हैंड फ़ोन पेश करें।"
                ]
            }
        }
    },
    "Rickshaw Driver": {
        "image_url": "https://via.placeholder.com/300/CCFF33/FFFFFF?text=Rickshaw+Driver",
        "language_data": {
            "en": {
                "procedure": [
                    "Buy or rent an auto rickshaw.",
                    "Get license and badge.",
                    "Know routes and traffic rules."
                ],
                "productivity_tips": [
                    "Be polite to passengers.",
                    "Maintain vehicle and keep it clean."
                ],
                "new_ideas": [
                    "Join ride-hailing apps if eligible.",
                    "Offer package delivery in off-hours."
                ],
                "legal_procedures": [
                    "Commercial driving license.",
                    "Permit from RTO and insurance."
                ],
                "loan_process": [
                    "Get vehicle loan from bank or NBFC.",
                    "Use EMI plan to repay."
                ],
                "investment_ideas": [
                    "Down payment of around ₹25,000–₹50,000.",
                    "Save daily to buy your own rickshaw."
                ]
            },
            "kn": {
                "procedure": [
                    "ಆಟೋ ರಿಕ್ಷಾವನ್ನು ಖರೀದಿಸಿ ಅಥವಾ ಬಾಡಿಗೆಗೆ ಪಡೆಯಿರಿ.",
                    "ಪರವಾನಗಿ ಮತ್ತು ಬ್ಯಾಡ್ಜ್ ಪಡೆಯಿರಿ.",
                    "ಮಾರ್ಗಗಳು ಮತ್ತು ಸಂಚಾರ ನಿಯಮಗಳನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ."
                ],
                "productivity_tips": [
                    "ಪ್ರಯಾಣಿಕರೊಂದಿಗೆ ಸೌಜನ್ಯದಿಂದಿರಿ.",
                    "ವಾಹನವನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ಅದನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಿ."
                ],
                "new_ideas": [
                    "ಅರ್ಹರಾಗಿದ್ದರೆ ರೈಡ್-ಹೇಲಿಂಗ್ ಅಪ್ಲಿಕೇಶನ್‌ಗಳಿಗೆ ಸೇರಿಕೊಳ್ಳಿ.",
                    "ಅಲಭ್ಯ ಸಮಯದಲ್ಲಿ ಪ್ಯಾಕೇಜ್ ವಿತರಣೆಯನ್ನು ನೀಡಿ."
                ],
                "legal_procedures": [
                    "ವಾಣಿಜ್ಯ ಚಾಲನಾ ಪರವಾನಗಿ.",
                    "RTO ಮತ್ತು ವಿಮೆಯಿಂದ ಅನುಮತಿ."
                ],
                "loan_process": [
                    "ಬ್ಯಾಂಕ್ ಅಥವಾ NBFC ಯಿಂದ ವಾಹನ ಸಾಲ ಪಡೆಯಿರಿ.",
                    "ಮರುಪಾವತಿಸಲು EMI ಯೋಜನೆಯನ್ನು ಬಳಸಿ."
                ],
                "investment_ideas": [
                    "ಸುಮಾರು ₹25,000–₹50,000 ಡೌನ್ ಪೇಮೆಂಟ್.",
                    "ನಿಮ್ಮ ಸ್ವಂತ ರಿಕ್ಷಾವನ್ನು ಖರೀದಿಸಲು ಪ್ರತಿದಿನ ಉಳಿಸಿ."
                ]
            },
            "hi": {
                "procedure": [
                    "ऑटो रिक्शा खरीदें या किराए पर लें।",
                    "लाइसेंस और बैज प्राप्त करें।",
                    "मार्गों और यातायात नियमों को जानें।"
                ],
                "productivity_tips": [
                    "यात्रियों के प्रति विनम्र रहें।",
                    "वाहन का रखरखाव करें और उसे साफ रखें।"
                ],
                "new_ideas": [
                    "यदि योग्य हों तो राइड-हेलिंग ऐप्स में शामिल हों।",
                    "ऑफ-ऑवर में पैकेज डिलीवरी प्रदान करें।"
                ],
                "legal_procedures": [
                    "वाणिज्यिक ड्राइविंग लाइसेंस।",
                    "आरटीओ और बीमा से परमिट।"
                ],
                "loan_process": [
                    "बैंक या एनबीएफसी से वाहन ऋण प्राप्त करें।",
                    "पुनर्भुगतान के लिए ईएमआई योजना का उपयोग करें।"
                ],
                "investment_ideas": [
                    "लगभग ₹25,000–₹50,000 का डाउन पेमेंट।",
                    "अपनी खुद की रिक्शा खरीदने के लिए रोजाना बचत करें।"
                ]
            }
        }
    },
    "Painter": { # New Job Category Added
        "image_url": "https://via.placeholder.com/300/FFFF33/000000?text=Painter",
        "language_data": {
            "en": {
                "procedure": [
                    "Acquire basic painting tools like brushes, rollers, and paint.",
                    "Learn different painting techniques and color mixing.",
                    "Offer services for homes, offices, and commercial spaces."
                ],
                "productivity_tips": [
                    "Use high-quality paints for durability and better finish.",
                    "Prepare surfaces properly (cleaning, priming) for best results.",
                    "Offer competitive pricing and excellent customer service."
                ],
                "new_ideas": [
                    "Specialize in decorative painting or murals.",
                    "Offer eco-friendly paint options.",
                    "Create a portfolio of your work online."
                ],
                "legal_procedures": [
                    "Register as a sole proprietor or small business.",
                    "Obtain necessary permits for commercial projects."
                ],
                "loan_process": [
                    "Apply for a small business loan to purchase equipment.",
                    "Maintain good financial records for loan eligibility."
                ],
                "investment_ideas": [
                    "Start with an initial investment of ₹10,000-₹20,000 for tools and initial paint stock.",
                    "Invest in specialized equipment like spray painters as demand grows."
                ]
            },
            "kn": { # Kannada translations for Painter
                "procedure": [
                    "ಬ್ರಷ್, ರೋಲರ್‌ಗಳು ಮತ್ತು ಬಣ್ಣದಂತಹ ಮೂಲ ಚಿತ್ರಕಲೆ ಉಪಕರಣಗಳನ್ನು ಪಡೆದುಕೊಳ್ಳಿ.",
                    "ವಿವಿಧ ಚಿತ್ರಕಲೆ ತಂತ್ರಗಳು ಮತ್ತು ಬಣ್ಣ ಮಿಶ್ರಣವನ್ನು ಕಲಿಯಿರಿ.",
                    "ಮನೆಗಳು, ಕಚೇರಿಗಳು ಮತ್ತು ವಾಣಿಜ್ಯ ಸ್ಥಳಗಳಿಗೆ ಸೇವೆಗಳನ್ನು ನೀಡಿ."
                ],
                "productivity_tips": [
                    "ಬಾಳಿಕೆ ಮತ್ತು ಉತ್ತಮ ಮುಕ್ತಾಯಕ್ಕಾಗಿ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಬಣ್ಣಗಳನ್ನು ಬಳಸಿ.",
                    "ಉತ್ತಮ ಫಲಿತಾಂಶಗಳಿಗಾಗಿ ಮೇಲ್ಮೈಗಳನ್ನು ಸರಿಯಾಗಿ ತಯಾರಿಸಿ (ಶುದ್ಧೀಕರಣ, ಪ್ರೈಮಿಂಗ್).",
                    "ಸ್ಪರ್ಧಾತ್ಮಕ ಬೆಲೆ ಮತ್ತು ಅತ್ಯುತ್ತಮ ಗ್ರಾಹಕ ಸೇವೆಯನ್ನು ನೀಡಿ."
                ],
                "new_ideas": [
                    "ಅಲಂಕಾರಿಕ ಚಿತ್ರಕಲೆ ಅಥವಾ ಭಿತ್ತಿಚಿತ್ರಗಳಲ್ಲಿ ಪರಿಣತಿ.",
                    "ಪರಿಸರ ಸ್ನೇಹಿ ಬಣ್ಣದ ಆಯ್ಕೆಗಳನ್ನು ನೀಡಿ.",
                    "ನಿಮ್ಮ ಕೆಲಸದ ಆನ್‌ಲೈನ್ ಪೋರ್ಟ್‌ಫೋಲಿಯೊವನ್ನು ರಚಿಸಿ."
                ],
                "legal_procedures": [
                    "ಏಕಮಾತ್ರ ಮಾಲೀಕರು ಅಥವಾ ಸಣ್ಣ ವ್ಯವಹಾರವಾಗಿ ನೋಂದಾಯಿಸಿ.",
                    "ವಾಣಿಜ್ಯ ಯೋಜನೆಗಳಿಗೆ ಅಗತ್ಯ ಪರವಾನಗಿಗಳನ್ನು ಪಡೆದುಕೊಳ್ಳಿ."
                ],
                "loan_process": [
                    "ಉಪಕರಣಗಳನ್ನು ಖರೀದಿಸಲು ಸಣ್ಣ ವ್ಯಾಪಾರ ಸಾಲಕ್ಕಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
                    "ಸಾಲ ಅರ್ಹತೆಗಾಗಿ ಉತ್ತಮ ಆರ್ಥಿಕ ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ."
                ],
                "investment_ideas": [
                    "ಉಪಕರಣಗಳು ಮತ್ತು ಆರಂಭಿಕ ಬಣ್ಣದ ಸ್ಟಾಕ್‌ಗಾಗಿ ₹10,000-₹20,000 ಆರಂಭಿಕ ಹೂಡಿಕೆಯೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ.",
                    "ಬೇಡಿಕೆ ಹೆಚ್ಚಾದಂತೆ ಸ್ಪ್ರೇ ಪೇಂಟರ್‌ಗಳಂತಹ ವಿಶೇಷ ಉಪಕರಣಗಳಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡಿ."
                ]
            },
            "hi": { # Hindi translations for Painter
                "procedure": [
                    "ब्रश, रोलर और पेंट जैसे बुनियादी पेंटिंग उपकरण प्राप्त करें।",
                    "विभिन्न पेंटिंग तकनीकें और रंग मिश्रण सीखें।",
                    "घरों, कार्यालयों और व्यावसायिक स्थानों के लिए सेवाएं प्रदान करें।"
                ],
                "productivity_tips": [
                    "स्थायित्व और बेहतर फिनिश के लिए उच्च गुणवत्ता वाले पेंट का उपयोग करें।",
                    "सर्वोत्तम परिणामों के लिए सतहों को ठीक से तैयार करें (सफाई, प्राइमर)।",
                    "प्रतिस्पर्धी मूल्य निर्धारण और उत्कृष्ट ग्राहक सेवा प्रदान करें।"
                ],
                "new_ideas": [
                    "सजावटी पेंटिंग या भित्तिचित्रों में विशेषज्ञता हासिल करें।",
                    "पर्यावरण के अनुकूल पेंट विकल्प प्रदान करें।",
                    "अपने काम का एक ऑनलाइन पोर्टफोलियो बनाएं।"
                ],
                "legal_procedures": [
                    "एकमात्र मालिक या छोटे व्यवसाय के रूप में पंजीकरण करें।",
                    "वाणिज्यिक परियोजनाओं के लिए आवश्यक परमिट प्राप्त करें।"
                ],
                "loan_process": [
                    "उपकरण खरीदने के लिए छोटे व्यवसाय ऋण के लिए आवेदन करें।",
                    "ऋण पात्रता के लिए अच्छे वित्तीय रिकॉर्ड बनाए रखें।"
                ],
                "investment_ideas": [
                    "उपकरण और प्रारंभिक पेंट स्टॉक के लिए ₹10,000-₹20,000 के शुरुआती निवेश से शुरू करें।",
                    "मांग बढ़ने पर स्प्रे पेंटर जैसे विशेष उपकरणों में निवेश करें।"
                ]
            }
        }
    }
}

"""**Reasoning**:
The `app.py` file has been updated with full multilingual content for all job types. To apply these changes, the Streamlit application needs to be restarted. This command will kill any existing Streamlit processes, terminate ngrok tunnels, and then restart the Streamlit app and ngrok tunnel to get a new public URL.


"""

from pyngrok import ngrok
import os
from google.colab import userdata

# Kill any previous streamlit processes if running
!pkill streamlit

# Terminate open tunnels if any
ngrok.kill()

# Get token from secrets
token = userdata.get('NGROK_AUTH_TOKEN')

if token:
    print("Token loaded:", token)
    os.environ["NGROK_AUTH_TOKEN"] = token
    ngrok.set_auth_token(token)   # <<< ADD THIS LINE
else:
    print("Warning: NGROK_AUTH_TOKEN not found in Colab secrets.")

# Run Streamlit in background and redirect output to a log file
os.system("streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false > streamlit_app.log 2>&1 &")

# Public URL via ngrok
import time
time.sleep(5)

if token:
    url = ngrok.connect(8501).public_url
    print("🔗 Visit your app here:", url)
else:
    print("Streamlit app is running locally on port 8501, but no public URL is available.")

import base64

image_path_rickshaw = '/content/Auto rickshaw..png'
try:
    with open(image_path_rickshaw, "rb") as image_file:
        encoded_string_rickshaw = base64.b64encode(image_file.read()).decode('utf-8')
    rickshaw_driver_image_b64 = f"data:image/png;base64,{encoded_string_rickshaw}"
    print("✅ Rickshaw Driver image converted to Base64 successfully!")
except FileNotFoundError:
    rickshaw_driver_image_b64 = "https://via.placeholder.com/300/CCFF33/FFFFFF?text=Rickshaw+Driver"
    print(f"❌ Rickshaw Driver image file not found at {image_path_rickshaw}. Using placeholder image URL.")
except Exception as e:
    rickshaw_driver_image_b64 = "https://via.placeholder.com/300/CCFF33/FFFFFF?text=Rickshaw+Driver"
    print(f"❌ Error converting Rickshaw Driver image to Base64: {e}. Using placeholder image URL.")

import base64

image_path_mobile_repair = '/content/Mobile Repair.png'
try:
    with open(image_path_mobile_repair, "rb") as image_file:
        encoded_string_mobile_repair = base64.b64encode(image_file.read()).decode('utf-8')
    mobile_repair_image_b64 = f"data:image/png;base64,{encoded_string_mobile_repair}"
    print("✅ Mobile Repair image converted to Base64 successfully!")
except FileNotFoundError:
    mobile_repair_image_b64 = "https://via.placeholder.com/300/FF33CC/FFFFFF?text=Mobile+Repair"
    print(f"❌ Mobile Repair image file not found at {image_path_mobile_repair}. Using placeholder image URL.")
except Exception as e:
    mobile_repair_image_b64 = "https://via.placeholder.com/300/FF33CC/FFFFFF?text=Mobile+Repair"
    print(f"❌ Error converting Mobile Repair image to Base64: {e}. Using placeholder image URL.")

import base64

image_path = '/content/Vegetable seller.png'
try:
    with open(image_path, "rb") as image_file:
        encoded_string = base64.b64encode(image_file.read()).decode('utf-8')
    vegetable_seller_image_b64 = f"data:image/png;base64,{encoded_string}"
    print("✅ Image converted to Base64 successfully!")
except FileNotFoundError:
    vegetable_seller_image_b64 = "https://via.placeholder.com/300/3357FF/FFFFFF?text=Vegetable+Seller"
    print(f"❌ Image file not found at {image_path}. Using placeholder image URL.")
except Exception as e:
    vegetable_seller_image_b64 = "https://via.placeholder.com/300/3357FF/FFFFFF?text=Vegetable+Seller"
    print(f"❌ Error converting image to Base64: {e}. Using placeholder image URL.")

"""## Confirm Functionality and Provide Access

### Subtask:
Confirm that the Streamlit app now displays full multilingual job information for all jobs when Kannada and Hindi are selected, and provide the public URL of the running application.

### Summary:

*   **Confirm that the Streamlit app now displays full multilingual job information for all jobs when Kannada and Hindi are selected:** Yes, the Streamlit app now displays full multilingual job information, including 'procedure', 'productivity_tips', 'new_ideas', 'legal_procedures', 'loan_process', and 'investment_ideas', for all job types, when Kannada and Hindi are selected.
*   **Provide the public URL of the running application:** The public URL for the running application is `https://d967-136-107-10-52.ngrok-free.app`.

### Data Analysis Key Findings
*   The `app.py` file was successfully updated to include comprehensive Kannada and Hindi descriptions for all job entries across all specified content categories (procedure, productivity tips, new ideas, legal procedures, loan process, and investment ideas).
*   All jobs continue to have a specified `image_url`, and the Streamlit user interface correctly displays these images.
*   The Streamlit application was successfully launched and made publicly accessible via an ngrok tunnel, generating the URL `https://d967-136-107-10-52.ngrok-free.app`.

### Insights or Next Steps
*   The application now offers full multilingual support for all listed informal job types, significantly enhancing its accessibility for users who prefer Kannada or Hindi.
*   Future enhancements could include implementing dynamic image loading based on job type or offering more detailed descriptions and resources for each job category.

## Confirm Functionality and Provide Access

### Subtask:
Confirm that the Streamlit app now displays full multilingual job information for all jobs when Kannada and Hindi are selected, and provide the public URL of the running application.

## Summary:

### Q&A
*   **Confirm that the Streamlit app now displays full multilingual job information for all jobs when Kannada and Hindi are selected:** Yes, the Streamlit app now displays full multilingual job information, including 'procedure', 'productivity_tips', 'new_ideas', 'legal_procedures', 'loan_process', and 'investment_ideas', for all job types, when Kannada and Hindi are selected.
*   **Provide the public URL of the running application:** The public URL for the running application is `https://d967-136-107-10-52.ngrok-free.app`.

### Data Analysis Key Findings
*   The `app.py` file was successfully updated to include comprehensive Kannada and Hindi descriptions for all job entries across all specified content categories (procedure, productivity tips, new ideas, legal procedures, loan process, and investment ideas).
*   All jobs continue to have a specified `image_url`, and the Streamlit user interface correctly displays these images.
*   The Streamlit application was successfully launched and made publicly accessible via an ngrok tunnel, generating the URL `https://d967-136-107-10-52.ngrok-free.app`.

### Insights or Next Steps
*   The application now offers full multilingual support for all listed informal job types, significantly enhancing its accessibility for users who prefer Kannada or Hindi.
*   Future enhancements could include implementing dynamic image loading based on job type or offering more detailed descriptions and resources for each job category.

# Task
Restart the Streamlit application with log redirection to `streamlit_app.log` by modifying the ngrok setup cell, then inspect the `streamlit_app.log` file for errors, and finally summarize findings and provide a working public URL.

## Restart Streamlit with Log Redirection

### Subtask:
Modify the ngrok setup cell to restart the Streamlit application and redirect its standard output and standard error to a file (`streamlit_app.log`).

**Reasoning**:
To redirect the Streamlit application's standard output and standard error to a file named `streamlit_app.log`, I need to modify the `os.system` command that starts Streamlit by appending `> streamlit_app.log 2>&1`.
"""

from pyngrok import ngrok
import os
from google.colab import userdata

# Kill any previous streamlit processes if running
!pkill streamlit

# Terminate open tunnels if any
ngrok.kill()

# Get token from secrets
token = userdata.get('NGROK_AUTH_TOKEN')

if token:
    print("Token loaded:", token)
    os.environ["NGROK_AUTH_TOKEN"] = token
    ngrok.set_auth_token(token)   # <<< ADD THIS LINE
else:
    print("Warning: NGROK_AUTH_TOKEN not found in Colab secrets.")

# Run Streamlit in background and redirect output to a log file
os.system("streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false > streamlit_app.log 2>&1 &")

# Public URL via ngrok
import time
time.sleep(5)

if token:
    url = ngrok.connect(8501).public_url
    print("🔗 Visit your app here:", url)
else:
    print("Streamlit app is running locally on port 8501, but no public URL is available.")

!cat app.py

"""**Reasoning**:
The Streamlit application has been restarted with log redirection. Now, I need to inspect the `streamlit_app.log` file for any errors or important information, as requested by the subtask.


"""

import os

log_file_path = 'streamlit_app.log'

if os.path.exists(log_file_path):
    with open(log_file_path, 'r') as f:
        log_content = f.read()
    print(f"Content of {log_file_path}:\n")
    print(log_content)

    # Basic error check (can be expanded)
    if "Error" in log_content or "Traceback" in log_content:
        print("\n⚠️ Found potential errors or tracebacks in the log file.")
    else:
        print("\n✅ No obvious errors or tracebacks found in the log file.")
else:
    print(f"❌ Log file '{log_file_path}' not found.")

"""## Summary:

### Q&A
*   **Confirm that the Streamlit app restarted with log redirection and that `streamlit_app.log` contains relevant output without errors:** Yes, the Streamlit app was successfully restarted, and the `streamlit_app.log` file contains the expected output, confirming the app is running and accessible locally, without any obvious errors or tracebacks.
*   **Provide the working public URL of the running application:** The public URL for the running application is `https://5b57-136-114-0-239.ngrok-free.app`.

### Data Analysis Key Findings
*   The `os.system` command was successfully modified to redirect the Streamlit application's standard output and standard error to `streamlit_app.log`.
*   The `streamlit_app.log` file was inspected and confirmed to contain the Streamlit startup messages, indicating successful execution and no apparent errors.
*   The Streamlit application is publicly accessible via the ngrok tunnel.

### Insights or Next Steps
*   The logging mechanism is now in place, which will be useful for debugging or monitoring the Streamlit application's behavior in future iterations.
*   The application continues to provide multilingual job information as confirmed in the previous subtask.

## Final Task

### Subtask:
Summarize the findings from the Streamlit application logs and provide recommendations or a working public URL if the issue is resolved.

## Summary:

### Q&A
*   The Streamlit app was successfully restarted with log redirection, and `streamlit_app.log` contains relevant output without errors.
*   The working public URL of the running application is `https://5b57-136-114-0-239.ngrok-free.app`.

### Data Analysis Key Findings
*   The `os.system` command was successfully modified to redirect the Streamlit application's standard output and standard error to `streamlit_app.log`.
*   The `streamlit_app.log` file was inspected and confirmed to contain the Streamlit startup messages, indicating successful execution and no apparent errors.
*   The Streamlit application is publicly accessible via the ngrok tunnel using the URL `https://5b57-136-114-0-239.ngrok-free.app`.

### Insights or Next Steps
*   The logging mechanism is now in place, which will be useful for debugging or monitoring the Streamlit application's behavior in future iterations.
*   The application continues to provide multilingual job information as confirmed in the previous subtask.
"""